version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: aiagent
      POSTGRES_DB: agentdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
